name: insurance-platform

description: "Repositório Monorepo para a plataforma de seguros"

structure:
  backend:
    services:
      - auth-service
      - clients-service
      - payments-service
      - claims-service
      - BFF
    shared-libs: []
    docker: []
    infra: []
  frontend:
    web-app: []
  devops:
    ci-cd: []
    k8s: []
  docs: []
  .github/workflows: []

files:
  - README.md
  - .gitignore
  - docker-compose.yml

docker-compose.yml:
  version: '3.8'
  services:
    postgres:
      image: postgres:15
      container_name: insurance-db
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

    redis:
      image: redis:alpine
      container_name: insurance-redis
      restart: always
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]

  volumes:
    pgdata: {}
